[package]
name = "sketch-space-time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

macroquad = "0.3.0"
rand = "0.8.5"
# realfft = "3.0.0"
rustfft = "6.0.1"
# fft2d = "0.1.0"
num-complex = "0.4.2"